# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-11 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speedtest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_ip', models.CharField(max_length=16)),
                ('private_ip', models.CharField(max_length=16)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_wifi', models.BooleanField()),
                ('wifi_ssid', models.CharField(max_length=50)),
                ('wifi_strength', models.IntegerField()),
                ('download', models.FloatField()),
                ('upload', models.FloatField()),
                ('imei', models.CharField(max_length=16)),
                ('carrier', models.CharField(max_length=16)),
                ('signal_strength', models.IntegerField()),
                ('network_type', models.IntegerField()),
                ('network_strength', models.IntegerField()),
                ('ping', models.FloatField()),
            ],
        ),
    ]
