# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-11 09:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speedtest',
            name='time',
            field=models.CharField(default=datetime.datetime(2016, 7, 11, 9, 14, 5, 461189, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
