# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-12 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_speedtest_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='speedtest',
            name='address',
            field=models.CharField(default=None, max_length=16),
        ),
        migrations.AddField(
            model_name='speedtest',
            name='cell_id',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speedtest',
            name='key',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speedtest',
            name='testid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speedtest',
            name='unkown',
            field=models.CharField(default=None, max_length=16),
        ),
    ]
