# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-14 04:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20160712_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speedtest',
            name='address',
        ),
        migrations.RemoveField(
            model_name='speedtest',
            name='cell_id',
        ),
        migrations.RemoveField(
            model_name='speedtest',
            name='key',
        ),
        migrations.RemoveField(
            model_name='speedtest',
            name='testid',
        ),
        migrations.RemoveField(
            model_name='speedtest',
            name='unkown',
        ),
    ]
